# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-13 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0004_auto_20181012_1836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Rate',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='review',
            new_name='rate',
        ),
    ]
