# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-13 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0007_project_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='post',
        ),
    ]
