# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-14 10:53
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0010_auto_20181013_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
