# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-14 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0011_auto_20181014_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwwwardsCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(max_length=55)),
                ('usability', models.CharField(max_length=55)),
                ('content', models.CharField(max_length=55)),
            ],
        ),
    ]
