# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0012_awwwardscriteria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AwwwardsCriteria',
        ),
    ]
